export const ALL_ACTIVITIES = [
	{
		name: "Setting System",
		code: "setting_system",
		title: "setting_system.title",
		id: 1,
		keyCheckBox: [
			"account_list_view",
			"account_list_edit",
			"account_create",
			"account_view",
			"permission_add_in_account",
			"account_edit",
			"signup_list_view",
			"signup_approve",
			"activity_list_view",
			"role_list_view",
			"info_edit_in_role",
			"permission_edit_in_role",
			"account_add_into_role",
		],
		children: [
			{
				name: "Accounts Management",
				code: "setting_system.accounts_management",
				title: "setting_system.accounts_management",
				id: 2,
				keyCheckBox: [
					"account_list_view",
					"account_list_edit",
					"account_create",
					"account_view",
					"permission_add_in_account",
					"account_edit",
					"signup_list_view",
					"signup_approve",
				],
				children: [
					{
						code: "account_list_view",
						title: "account_list_view",
						keyCheckBox: ["account_list_view"],
						name: "View listing accounts",
						id: 1,
					},
					{
						code: "account_list_edit",
						title: "account_list_edit",
						keyCheckBox: ["account_list_edit"],
						name: "Edit Status, Role, Line Manager",
						id: 2,
					},
					{
						code: "account_create",
						title: "account_create",
						keyCheckBox: ["account_create"],
						name: "Create account",
						id: 3,
					},
					{
						code: "account_view",
						title: "account_view",
						keyCheckBox: ["account_view"],
						name: "View detail account",
						id: 4,
					},
					{
						code: "permission_add_in_account",
						title: "permission_add_in_account",
						keyCheckBox: ["permission_add_in_account"],
						name: "Add permissions",
						id: 5,
					},
					{
						code: "account_edit",
						title: "account_edit",
						keyCheckBox: ["account_edit"],
						name: "Edit account",
						id: 6,
					},
					{
						code: "signup_list_view",
						title: "signup_list_view",
						keyCheckBox: ["signup_list_view"],
						name: "View listing sign-up requests",
						id: 7,
					},
					{
						code: "signup_approve",
						title: "signup_approve",
						keyCheckBox: ["signup_approve"],
						name: "Approve sign-up request",
						id: 8,
					},
				],
			},
			{
				name: "Roles Management",
				code: "setting_system.roles_management",
				title: "setting_system.roles_management",
				id: 3,
				keyCheckBox: [
					"activity_list_view",
					"role_list_view",
					"info_edit_in_role",
					"permission_edit_in_role",
					"account_add_into_role",
				],
				children: [
					{
						code: "activity_list_view",
						title: "activity_list_view",
						keyCheckBox: ["activity_list_view"],
						name: "View listing permission activities",
						id: 9,
					},
					{
						code: "role_list_view",
						title: "role_list_view",
						keyCheckBox: ["role_list_view"],
						name: "View listing roles",
						id: 10,
					},
					{
						code: "info_edit_in_role",
						title: "info_edit_in_role",
						keyCheckBox: ["info_edit_in_role"],
						name: "Edit role info",
						id: 11,
					},
					{
						code: "permission_edit_in_role",
						title: "permission_edit_in_role",
						keyCheckBox: ["permission_edit_in_role"],
						name: "Edit role permission",
						id: 12,
					},
					{
						code: "account_add_into_role",
						title: "account_add_into_role",
						keyCheckBox: ["account_add_into_role"],
						name: "Add account into role",
						id: 13,
					},
				],
			},
			// {
			// 	name: "Organizations management",
			// 	code: "setting_system.organizations_management",
			// 	id: 4,
			// 	keyCheckBox: [],
			// 	children: [],
			// },
		],
	},
	{
		name: "Profit Simulation",
		code: "profit_simulation",
		title: "profit_simulation.title",
		id: 21,
		keyCheckBox: [
			"ps_calculate_profit_simulation",
			"ps_record_save",
			"ps_saved_list_view",
			"ps_saved_list_view_in_organization",
			"ps_record_view",
			"ps_record_view_in_organization",
			"ps_assumption_view",
			"ps_assumption_manage_update",
		],
		children: [
			{
				name: "Calculate profit simulation",
				code: "profit_simulation.calculate_profit_simulation",
				title: "profit_simulation.calculate_profit_simulation",
				id: 22,
				keyCheckBox: ["ps_calculate_profit_simulation", "ps_record_save"],
				children: [
					{
						code: "ps_calculate_profit_simulation",
						title: "ps_calculate_profit_simulation",
						keyCheckBox: ["ps_calculate_profit_simulation"],
						name: "Calculate Profit Simulation",
						id: 21,
					},
					{
						code: "ps_record_save",
						title: "ps_record_save",
						keyCheckBox: ["ps_record_save"],
						name: "Save profit simulation record with selected calculated row result",
						id: 27,
					},
				],
			},
			{
				name: "Manage profit simulation result",
				code: "profit_simulation.manage_profit_simulation_result",
				title: "profit_simulation.manage_profit_simulation_result",
				keyCheckBox: [
					"ps_saved_list_view",
					"ps_saved_list_view_in_organization",
					"ps_record_view",
					"ps_record_view_in_organization",
				],
				id: 23,
				children: [
					{
						code: "ps_saved_list_view",
						title: "ps_saved_list_view",
						keyCheckBox: ["ps_saved_list_view"],
						name: "View saved list profit simulation record",
						id: 28,
					},
					{
						code: "ps_saved_list_view_in_organization",
						title: "ps_saved_list_view_in_organization",
						keyCheckBox: ["ps_saved_list_view_in_organization"],
						name: "View saved list profit simulation record of employee in the organization",
						id: 31,
					},
					{
						code: "ps_record_view",
						title: "ps_record_view",
						keyCheckBox: ["ps_record_view"],
						name: "View a profit simulation record",
						id: 34,
					},
					{
						code: "ps_record_view_in_organization",
						title: "ps_record_view_in_organization",
						keyCheckBox: ["ps_record_view_in_organization"],
						name: "View a profit simulation record of employee in the organization",
						id: 37,
					},
				],
			},
			{
				name: "Manage Assumption",
				code: "profit_simulation.manage_assumption",
				title: "profit_simulation.manage_assumption",
				id: 41,
				keyCheckBox: ["ps_assumption_view", "ps_assumption_manage_update"],
				children: [
					{
						code: "ps_assumption_view",
						title: "ps_assumption_view",
						name: "View assumption",
						keyCheckBox: ["ps_assumption_view"],
						id: 41,
					},
					{
						code: "ps_assumption_manage_update",
						title: "ps_assumption_manage_update",
						name: "Manage assumption",
						keyCheckBox: ["ps_assumption_manage_update"],
						id: 42,
					},
				],
			},
		],
	},
	{
		name: "Product Information",
		code: "product_information",
		id: 61,
		keyCheckBox: [
			"pi_master_data_view",
			"pi_request_list_view",
			"pi_many_request_approve_decline",
			"pi_a_request_view",
			"pi_a_request_approve_decline",
			"pi_a_request_edit",
			"pi_approval_list_view",
			"pi_new_product_list_view",
			"pi_new_product_assign_sales",
			"pi_assign_new_product_list_view",
			"pi_category_tree_view",
			"pi_root_category_add",
		],
		children: [
			{
				name: "Product Master Data",
				code: "product_information.product_master_data",
				id: 62,
				keyCheckBox: ["pi_master_data_view"],
				children: [
					{
						code: "pi_master_data_view",
						keyCheckBox: ["pi_master_data_view"],
						name: "View Product Master Data",
						id: 61,
					},
				],
			},
			{
				name: "Update Requests List",
				code: "product_information.update_requests_list",
				id: 63,
				keyCheckBox: [
					"pi_request_list_view",
					"pi_many_request_approve_decline",
					"pi_a_request_view",
					"pi_a_request_approve_decline",
					"pi_a_request_edit",
					"pi_approval_list_view",
				],
				children: [
					{
						code: "pi_request_list_view",
						keyCheckBox: ["pi_request_list_view"],
						name: "View Update Requests List",
						id: 62,
					},
					{
						code: "pi_many_request_approve_decline",
						keyCheckBox: ["pi_many_request_approve_decline"],
						name: "Approve or Decline many requests",
						id: 63,
					},
					{
						code: "pi_a_request_view",
						keyCheckBox: ["pi_a_request_view"],
						name: "View detail a request",
						id: 64,
					},
					{
						code: "pi_a_request_approve_decline",
						keyCheckBox: ["pi_a_request_approve_decline"],
						name: "Approve or Decline a requests",
						id: 65,
					},
					{
						code: "pi_a_request_edit",
						keyCheckBox: ["pi_a_request_edit"],
						name: "Edit a request",
						id: 66,
					},
					{
						code: "pi_approval_list_view",
						keyCheckBox: ["pi_approval_list_view"],
						name: "View Approved Requests List",
						id: 67,
					},
				],
			},
			{
				name: "Assign new SKU to Sales",
				code: "product_information.assign_new_sku_to_sales",
				id: 64,
				keyCheckBox: [
					"pi_new_product_list_view",
					"pi_new_product_assign_sales",
					"pi_assign_new_product_list_view",
				],
				children: [
					{
						code: "pi_new_product_list_view",
						keyCheckBox: ["pi_new_product_list_view"],
						name: "View new product list",
						id: 68,
					},
					{
						code: "pi_new_product_assign_sales",
						keyCheckBox: ["pi_new_product_assign_sales"],
						name: "Assign new product to Sales",
						id: 69,
					},
					{
						code: "pi_assign_new_product_list_view",
						keyCheckBox: ["pi_assign_new_product_list_view"],
						name: "View assigned product list",
						id: 70,
					},
				],
			},
			{
				name: "Manage Category",
				code: "product_information.manage_category",
				id: 65,
				keyCheckBox: ["pi_category_tree_view", "pi_root_category_add"],
				children: [
					{
						code: "pi_category_tree_view",
						keyCheckBox: ["pi_category_tree_view"],
						name: "View Category tree",
						id: 71,
					},
					{
						code: "pi_root_category_add",
						keyCheckBox: ["pi_root_category_add"],
						name: "Add a Root Category",
						id: 72,
					},
				],
			},
		],
	},
];

export const MAPPING_KEY_ACTIVITIES_ID = {
	account_list_view: 1,
	account_list_edit: 2,
	account_create: 3,
	account_view: 4,
	permission_add_in_account: 5,
	account_edit: 6,
	signup_list_view: 7,
	signup_approve: 8,
	activity_list_view: 9,
	role_list_view: 10,
	info_edit_in_role: 11,
	permission_edit_in_role: 12,
	account_add_into_role: 13,
	ps_calculate_profit_simulation: 21,
	ps_record_save: 27,
	ps_saved_list_view: 28,
	ps_saved_list_view_in_organization: 31,
	ps_record_view: 34,
	ps_record_view_in_organization: 37,
	ps_assumption_view: 41,
	ps_assumption_manage_update: 42,
	pi_master_data_view: 61,
	pi_request_list_view: 62,
	pi_many_request_approve_decline: 63,
	pi_a_request_view: 64,
	pi_a_request_approve_decline: 65,
	pi_a_request_edit: 66,
	pi_approval_list_view: 67,
	pi_new_product_list_view: 68,
	pi_new_product_assign_sales: 69,
	pi_assign_new_product_list_view: 70,
	pi_category_tree_view: 71,
	pi_root_category_add: 72,
};
