export const PATH = {
	HOME: "/",
	DETAIL: "/detail",
	EDIT: "/edit",
	LOGIN: "/login",
	LOGOUT: "/logout",
	REGISTER: "/register",
	RESET_PASSWORD: "/reset-password",
	PROFIT_SIMULATION: "/profit-simulation",
	VARIATIONS: "/variations",
	ASSUMPTION: "/assumption",
	CREATE: "/create",
	ACCOUNT_LIST: "/account-list",
	GROUP_PERMISSION: "/group-permission",
	ACTIVITIES_LIST: "/activities-list",
	PARTNER_LIST: "/partner-list",
	ITEMS_REPORT: "/items-report",
	PROFILE: "/profile",
	PRODUCT_MASTER: "/product-master",
	UPDATE_REQUEST_LIST: "/update-requests-list",
	ADD_PRODUCTS: "/add-products",
	CATEGORY: "/category",
	PREVIEW_SPREADSHEET_LIST: "/preview-spreadsheet-list",
	BULK_PRODUCT_SUBMISSIONS: "/bulk-product-submissions",
	CHANGE_LOG: "/change-log",
	LD:"/l&d",
	Learning_Development:"/learning-development",
	LDManage:"/ld-manage",
	LDScoreByMonthReport: '/score-by-month-report',
	LDAcademyRankingReport: '/academic-performance-ranking-report'

};
