import { ETypeCont } from "src/interface/profitSimulation.interface";

export const COLUMNS_VISIBILITY = {
	asin: true,
	brand: true,
	channel: true,
	cm_ex_di: true,
	cm_ex_ds: true,
	cm_ex_fba: true,
	cm_ex_mix_channel: true,
	cm_ex_percent_di: true,
	cm_ex_percent_ds: true,
	cm_ex_percent_fba: true,
	cm_ex_percent_mix_channel: true,
	cm_ex_percent_wh: true,
	cm_ex_wh: true,
	// cm_in_di: true,
	// cm_in_ds: true,
	// cm_in_fba: true,
	// cm_in_mix_channel: true,
	// cm_in_percent_di: true,
	// cm_in_percent_ds: true,
	// cm_in_percent_fba: true,
	// cm_in_percent_mix_channel: true,
	// cm_in_percent_wh: true,
	// cm_in_wh: true,
	competitor_bep: true,
	country: true,
	fob: true,
	image: true,
	is_blue: true,
	is_packaging_dimension: true,
	longest_side: true,
	max_loading_capacity: true,
	median_side: true,
	// net_profit_di: true,
	// net_profit_ds: true,
	// net_profit_fba: true,
	// net_profit_mix_channel: true,
	// net_profit_wh: true,
	rrp: true,
	shortest_side: true,
	size_tier: true,
	weight: true,
};
export const DEFAULT_VARIABLES = {
	percent_submit_to_amz_di: null,
	percent_submit_to_amz_ds: null,
	percent_submit_to_amz_wh: null,
	amz_refund_and_chargeback: null,
	mix_channel_di: null,
	mix_channel_ds: null,
	mix_channel_wh: null,
	mix_channel_fba: null,
	percent_mkt_fee: null,
	percent_price_discount: null,
	period: "",
	product_source: "",
	category: "",
	suggested_duty: null,
	type_of_cont_shipping: "",
};

export const DEFAULT_FILTER = {
	percent_submit_to_amz_di: 0.6,
	percent_submit_to_amz_ds: 0.7,
	percent_submit_to_amz_wh: 0.7,
	amz_refund_and_chargeback: 0.03,
	mix_channel_di: 0.7,
	mix_channel_ds: 0.3,
	mix_channel_wh: 0,
	mix_channel_fba: 0,
	percent_mkt_fee: 0.17,
	percent_price_discount: 0.1,
	period: "January– September",
	product_source: "",
	category: "",
	suggested_duty: 0.2887,
	suggested_duty_previous: 0,
	type_of_cont_shipping: ETypeCont.Cont40,
};

export const DEFAULT_VALUE_CALCULATOR_PS = {
	competitor_bep: 0,
	cm_in_di: 0,
	cm_in_ds: 0,
	cm_in_wh: 0,
	cm_in_fba: 0,
	cm_in_mix_channel: 0,
	cm_in_percent_di: 0,
	cm_in_percent_ds: 0,
	cm_in_percent_wh: 0,
	cm_in_percent_fba: 0,
	cm_in_percent_mix_channel: 0,
	cm_ex_di: 0,
	cm_ex_ds: 0,
	cm_ex_wh: 0,
	cm_ex_fba: 0,
	cm_ex_mix_channel: 0,
	cm_ex_percent_di: 0,
	cm_ex_percent_ds: 0,
	cm_ex_percent_wh: 0,
	cm_ex_percent_fba: 0,
	cm_ex_percent_mix_channel: 0,
	net_profit_di: 0,
	net_profit_ds: 0,
	net_profit_wh: 0,
	net_profit_fba: 0,
	net_profit_mix_channel: 0,
	net_ppm_di: 0,
	net_ppm_ds: 0,
	net_ppm_wh: 0,
	net_ppm_mix_channel: 0,
	net_ppm_percent_di: 0,
	net_ppm_percent_ds: 0,
	net_ppm_percent_wh: 0,
	net_ppm_percent_mix_channel: 0,
};
